#!/usr/bin/bash

#Get current conda env, and change back to it after the test
current_conda=$CONDA_DEFAULT_ENV


#Create a dummy environment
conda deactivate
conda create --name test-env python=3.9
conda activate test-env


#Download and install pyfa_tool
pip3 install PyFa-tool --upgrade





#run tests
cd ..
python tests/package_tests.py


#Back to initial conda env
conda deactivate
conda activate ${current_conda}

