#!/usr/bin/env bash

cd ..
#3 Uploading to testPyPi
echo "Uploading to testPyPI ..."
python3 -m twine upload --verbose -u __token__ -p pypi-AgENdGVzdC5weXBpLm9yZwIkYmZlYzVmMTEtNzdhMy00N2I2LTgxNmEtNzYxNDljMGU2NjgyAAIqWzMsImZhNTY0NjMwLWQ4MjMtNDU0Zi1hMzU4LThmODFkM2JjNWNhMSJdAAAGIFbiJUx3A4A_m8uc47yrtqceaFr7erEI-RFpxTd-Qk4e --repository testpypi dist/*
