name: Test pushed version

on: [push]

jobs:
#---- Version Control -----#
   versiontest:
     name: check if version is valid
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: get version
         id: 'version_info'
         run: |
           CURRENT_VERSION="$(grep -oP '__version__ = "\K\d+\.\d+\.\d+' pyfa_tool/__init__.py)"
           echo "current version (init) = ${CURRENT_VERSION}"
           echo "::set-output name=current_version::$CURRENT_VERSION"
           PYPROJECT_VERSION="$(grep -oP 'version = "\K\d+\.\d+\.\d+' pyproject.toml)"
           echo "current version (pyproject) = ${PYPROJECT_VERSION}"
           echo "::set-output name=pyproject_version::$PYPROJECT_VERSION"
       - name: version-is-correct
         if: ${{ steps.version_info.outputs.current_version != steps.version_info.outputs.pyproject_version }}
         run: |
           echo "version tags are not aligned!"
           exit 1

